services:

    laravel:
        build:
            context: .
        volumes:
            - ./:/var/www/html
        networks:
            - laravel_network
        ports:
            - 8000:80

    mysql:
        image: 'mysql/mysql-server:8.0'
        ports:
            - '${DB_PORT}:3306'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ALLOW_EMPTY_PASSWORD: 1
        volumes:
            - 'mysql_data:/var/lib/mysql'
        networks:
            - laravel_network
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        environment:
            PMA_HOST: '${DB_HOST}'
            PMA_PORT: '${DB_PORT}'
            PMA_USER: '${DB_USERNAME}'
            PMA_PASSWORD: '${DB_PASSWORD}'
        networks:
            - laravel_network
        ports:
            - 8080:80
        depends_on:
            - mysql

networks:
    laravel_network:
        driver: bridge

volumes:
    mysql_data:
        driver: local
